[[getting-started]]
= Getting Started

[partintro]
--
This section describes the software requirements and configuration settings for developing and running NeCTR v2.
--

[[development]]
== System Requirements
NeCTR v2 requires http://www.java.com[Java 8] and Spring Boot 1.2.2.RELEASE / Spring 4.1.5.RELEASE or above. Explicit build support
is provided for by Maven (3.2+).

|===
|Name |Version

|Java
|8.0

|Maven
|3.2+

|Eclipse
|Spring STS

|MongoDB
|2.6.3+

|===

== Developer Setup
There has been an attempt to minimise the amount of setup for getting a developer up and running with
NeCTR v2 application, but there are still a minimum set of steps that need to be taken. To ensure
the application can run please follow the instructions below in this section.

=== Java Installation
You should check your current Java installation before you begin:

[indent=0]
----
	$ java -version
----

If you don't already have Java 8 installed you can follow instructions at
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java JDK 8].

=== Maven Installation
NeCTR compatible with Apache Maven 3.2 or above. If you don't already have Maven
installed you can follow the instructions at http://maven.apache.org.

TIP: On many operating systems Maven can be installed via a package manager. If you're an
OSX Homebrew user try `brew install maven`. Ubuntu users can run
`sudo apt-get install maven`.

In order to have Maven connect to the project's link:http://10.240.43.25:8081/nexus[Nexus]
repository make sure your `settings.xml` is correctly configured.

Here is a typical `settings.xml` file:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<settings>
		<profiles>
			<profile>
				<id>nexus</id>
				<repositories>
					<repository>
						<id>central</id>
						<url>http://10.240.43.25:8081/nexus/content/groups/RoadRunnerCentral</url>
						<releases>
							<enabled>true</enabled>
						</releases>
						<snapshots>
							<enabled>true</enabled>
						</snapshots>
					</repository>
				</repositories>
				<pluginRepositories>
					<pluginRepository>
						<id>central</id>
						<url>http://10.240.43.25:8081/nexus/content/groups/RoadRunnerCentral</url>
						<releases>
							<enabled>true</enabled>
						</releases>
						<snapshots>
							<enabled>true</enabled>
						</snapshots>
					</pluginRepository>
				</pluginRepositories>
			</profile>
		</profiles>
		<activeProfiles>
			<activeProfile>nexus</activeProfile>
		</activeProfiles>
	</settings>
----
=== Eclipse Installation
Although it is possible to install other Eclipse distributions, the CPW project's
standard is to use the Spring Tool Suite. If you haven't done so already follow
the instructions at http://download.springsource.com/release/STS/doc/STS-installation_instructions.pdf[SpringSource ToolSuite].

=== MongoDB Installation
It is necessary to have a mongo instance up and running before starting up the NeCTR v2 application. If you don't already have MongoDB
installed you can follow the instructions at http://docs.mongodb.org/manual/installation/

=== Clone GIT Repository

[indent=0]
----
	$ git clone http://10.240.43.25:8080/nectr-v2-api
----

=== Build & Run Application

In the root of your cloned repository run `mvn clean install` and change directory to the `nectr-v2-api/target` directory:

[indent=0]
----
	$ cd nectr-v2-api/target
----

Make sure you have a MongoDB instance running on your environment before starting up the application:

[indent=0]
----
	$ mongod
----

Run the embedded container by invoking the Spring Boot Application:

[indent=0]
----
	$ java -jar nectr-v2-api-0.0.1-SNAPSHOT.jar
----

Test the application by invoking the Spring Boot health actuator:

[indent=0]
----
	$ curl http://localhost:8080/health
	{"status":"UP"}
----

== Additional Features
NeCTR v2 contains a few features to aid the interaction of the user with the API.

=== Swagger UI
Swagger is used to document the NeCTR v2 API. By using the link:https://github.com/springfox/springfox[Spring MVC integration for Swagger]
and link:https://github.com/swagger-api/swagger-ui[Swagger UI] projects, we are able to generate documentation out of Spring MVC Controllers and in addition
provide a simple testing platform for interacting with the NeCTR v2 API.

Swagger UI can be accessed link:{nectr-v2-root-path}/swagger/index.html[here].

=== Admin UI
NeCTR v2 comes prepackaged with Codecentric's link:https://github.com/codecentric/spring-boot-admin[Spring Boot Admin UI] which gives access to the
Spring Boot Actuator metrics for easier monitoring of the application at runtime.

The interface can be access link:{nectr-v2-root-path}/admin/index.html[here].

== Configuration
By default the `application.properties` is configured to run without change straight after cloning it from GIT. As
such a default set of properties have been defined which can then be overridden as required by the automated deployment jobs.

For a complete list of Spring Boot application properties please refer to the
link:http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[Spring Boot Documentation]
and https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-starter-client/README.md[Spring Boot Admin Documentation]

|===
|Name |Description

|spring.application.name (*)
|Name to be shown in the application list. Name of the ApplicationContext. Defaults to `nectr-v2-api`.

|spring.data.mongodb.uri (*)
|NeCTR v2 MongoDb connection URL. Defaults to `mongodb://localhost:27017/nectr-v2`.

|spring.boot.admin.url (*)
|URL of the spring-boot-admin application to register at. Defaults to `http://localhost:8080`.

|spring.boot.admin.client.url (*)
|Client-management-URL to register with. Can be overridden in case the reachable URL is different (e.g. Docker). Must be unique in registry. Defaults to `http://localhost:8080`.

|info.id
|N/A. Default to `nectr-v2-api`.

|info.version
|Version number to be shown in the Spring Boot Admin and Swagger application list. Defaults to `0.0.1-SNAPSHOT`.

|logging.file
|Path to the applications logfile for access via Spring Boot Admin. Defaults to `nectr-v2-api.log`.

|logback.access.enaled
|Http request and responses can be logged to the standard output if needed by enabling this flag to `true`. Defaults to `false`.

|server.port
|The embedded server port. Defaults to `8080`.

|server.contextPath
|The embedded server context path. Defaults to `/`.

|default.environment.id (*)
|Environment identifier used for retrieving data from. Defaults to `LOCAL`.

|default.environment.integration-host.url (*)
|Mule integration host MongoDB URL used to retrieve recorded integration data. Defaults to `localhost:27017`.

|default.environment.integration-host.dbName (*)
|Mule integration host MongoDB database name containing the integration recordings. Defaults to `integration`.

|default.environment.integration-host.collection (*)
|Mule integration host MongoDB collection containing the integration recordings. Defaults to `logs`.

|default.environment.application-host.url (**)
|HoneyBee application host MongoDB URL used to retrieve stored application xFlow data. Defaults to `localhost:27017`.

|default.environment.application-host.dbName (**)
|HoneyBee application host MongoDB database name containing the application xFlow data. Defaults to `application`.

|enable.application-host
|Flag used to configure NeCTRv2 so it creates Test Scenarios with data from HoneyBee. Defaults to `false`.

|===

(*) Mandatory fields

(**) Mandatory fields only when `enable.application-host=true`

=== Default Environment
The concept of a default environment in the NeCTR v2 application is crucial to the understanding of how is configured and deployed.
Without a default environment for NeCTR v2 to connect to the application is useless. Furthermore given that https://ews-tactical.atlassian.net/projects/NV/versions/10300[Phase 1] of the application is intended to
work without a HoneyBee host, it is mandatory that at the very least an Mule integration host is configured in the `application.properties`.

The `LoadDefaultEnvironmentListener` component in the application is responsible, at startup, to validate that the minimum amount settings are
properly configured in the `application.properties`. If this initial validation fails then the application will not start, throwing an `IllegalStateException`.

At the very minimum the following settings have to be present:

* `default.environment.id`
* `default.environment.integration-host.url`
* `default.environment.integration-host.dbName`
* `default.environment.integration-host.collection`

==== Application Host

If the NeCTR needs to access HoneyBee data when creating the test scenarios then the `enable.application-host=true` must be set.

Once this setting is enabled the following properties also become mandatory:

* `default.environment.application-host.url`
* `default.environment.application-host.dbName`

Note: `default.environment.application-host.collection` is not present. This is due to the fact that the collection name in HoneyBee MongoDB
is dynamic in nature with the journey name as its name. This is why, when the application host is enabled, that the journeyName parameter needs to be present in the Mule integration data.
This parameter is then used to query the right collection in the HoneyBee MongoDB.

== Development Control Services
DCSC tooling is used to build, deploy and govern the development of NeCTR v2. To raise a request please use https://adlm.accenture.com/jira/secure/Dashboard.jspa[ADLM JIRA]

=== Issue Tracking
Issues, bugs, and feature requests should be submitted to the following issue tracking system: link:https://ews-tactical.atlassian.net/projects/NV/summary[NeCTR v2 JIRA].

=== Continuous Integration
Builds and deployments can be tracked in Jenkins at:

* link:http://10.240.43.100:8080/job/nectr-v2-api-build/[Build Job]
* link:http://10.240.43.100:8080/view/nectr-v2-api-pipeline/[Deployment Pipeline]

=== Code Quality
For quality stats and test coverage check link:http://10.240.43.100:9000/sonar/dashboard/index/com.connectedworldservices.nectr:nectr-v2-api-parent:develop[Sonar].
